fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.7.0'
    nginx:
      repo: 'jfryman/nginx'
      ref: '0.2.7'
    apt:
      repo: 'puppetlabs/apt'
      ref: '2.1.1'
    concat:
      repo: 'puppetlabs/concat'
      ref: '1.2.4'
    vcsrepo:
      repo: 'puppetlabs/vcsrepo'
      ref: '1.3.1'
  symlinks:
    nc_nginx: "#{source_dir}"
