name          'thejandroman-nc_nginx'
version       '0.1.0'
source        'git@github.com:thejandroman/puppet-nc_nginx.git'
author        'thejandroman'
license       'Apache-2.0'
summary       'Install and configure Nginx according to NC's requirements.'
description   ''
project_page  'https://github.com/thejandroman/puppet-nc_nginx'

dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/vcsrepo'
dependency 'jfryman/nginx'
